### ISSUE TITLE
Signature is not displayed for function objects

### ISSUE THREAD

**Issue by PertuyF** [spyder-ide/docrepr#12]
Hi there,

I noticed that signature are correctly displayed for `class` objects, but not for `function` objects using `docrepr v.0.1.0` (pip install, python 3.4.3, windows 7 x64).
Actually the whole "Definition:" line is missing in the case of functions.

By the way, docrepr is really great when you want to generate a simple doc using Numpy style docstrings. At least it is far simpler than digging into Sphinx to get Numpy's style correctly rendered (can't get neither numpydoc nor napoleon working, but in my case PEBKAC as I am a complete noob at Sphinx at this time.)

Hope you'll keep going with docrepr!

**Comment by ccordoba12** [comment]
Could you post an example that's failing for you?

**Comment by PertuyF** [comment]
Sure, here is a minimal working example.
Signature from `functionSignature` is not displayed correctly, whereas it is OK for `ClassSignature`.
I just turned the `docrepr` usage example into a function called `renderDocString` for simplicity.

```
import webbrowser
import docrepr
from docrepr import sphinxify
from IPython.core.oinspect import Inspector

class ClassSignature():
    """
    Descritpion
    -----------
    Simple test for correct class signature documentation using ``docrepr``.
    """
    def __init__(self, arg1, arg2, *args, kwarg1=None, **kwargs):
        pass

def functionSignature(arg1, arg2, *args, kwarg1=None, **kwargs):
    """
    Description
    -----------
    Simple test for correct function signature documentation using ``docrepr``.
    """
    pass

def renderDocString(objName, obj, show=False):
    """
    Description
    -----------
    Simply generate HTML format docstring using docrepr.

    Args
    ----
    objName: ``string``
        object name
    obj: ``object``
        object from which the docstring will be rendered

    Kwargs
    ------
    show: ``bool``
        whether to automatically display the rendered file

    Return
    ------
    url: ``string``
        path to the rendered docstring as HTML file, stored in a temporary
        directory
    """
    oinfo = Inspector().info(obj)
    oinfo['name'] = objName
    url = docrepr.sphinxify.rich_repr(oinfo)
    if show:
        webbrowser.open_new_tab(url)
    return url

if __name__ == "__main__":
    renderDocString('functionSignature', functionSignature, show=True)
    renderDocString('ClassSignature', ClassSignature, show=True)
```

Just copy/paste this code to a script and it should work.

EDIT:
=====
I had a look at `sphinxify` however I am not sure to get the details of how everything works.
Yet, it seems that `init_template_vars()` prepares all object's info to be rendered by sphinx. And the signature part is likely to be reconstructed from `oinfo['argspecs']['args']`.

My guess is that it would be simpler to use `oinfo['definition']` for functions, and `oinfo['init_definition']` for classes, which both contain the object signature as a string. As discrimination between classes and functions is easy, this approach could work. However, I have no idea how this information can be used during the html/txt rendering.
But maybe I am missing some special case here that make it more complicated that it seems.
