### ISSUE TITLE
docrepr failing to import in readthedocs

### ISSUE THREAD

**Issue by takluyver** [spyder-ide/docrepr#15]
I just noticed that IPython builds are failing, with an error like this:

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipython/envs/latest/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 90, in <module>
    import docrepr.sphinxify as sphx
  File "/home/docs/checkouts/readthedocs.org/user_builds/ipython/envs/latest/lib/python3.5/site-packages/docrepr/sphinxify.py", line 53, in <module>
    CACHEDIR = tempfile.gettempdir() + osp.sep + 'docrepr-' + username
TypeError: Can't convert 'NoneType' object to str implicitly
```

I guess that maybe the `USER` environment variable isn't set on RTD?

**Comment by takluyver** [comment]
Ah, I see now that this was already fixed in #13. Can I ask for a new release with the fix in?

**Comment by SylvainCorlay** [comment]
cc @ccordoba12

**Comment by ccordoba12** [comment]
I'll do a new release during the weekend.

**Comment by takluyver** [comment]
Thanks Carlos. I'm not sure why it's only started failing recently; maybe the RTD infrastructure changed.

**Comment by takluyver** [comment]
Ping? ;-)

**Comment by ccordoba12** [comment]
Sorry, will do it later today. Please ping me again tomorrow if that's 
not the case ;-)

**Comment by ccordoba12** [comment]
This is done now! Thanks for your patience.

**Comment by takluyver** [comment]
Thanks @ccordoba12 :-)
