### ISSUE TITLE
Enable usage in the Notebook

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/docrepr#3]
I'd love to be able to make a  function/magic to display a rich HTML repr of the docstring in the Notebook. Unfortunately it seems a [naive implementation](https://notebooks.anaconda.org/dhirschfeld/docrepr-ipynb) doesn't  display properly. I guess I've got two questions:
1. Is this possible?
2. Are the problems something that needs to be fixed on the docrepr or IPython side?

If it is possible I'm happy to give it a go if I'm pointed in the right direction - I'm not too sharp with web technologies so am at a bit of a loss where to begin.

**Comment by ccordoba12** [comment]
Dave, of course this is next in my list ;-) But we have to wait until Jupyter 4.0 is released because it contains a crucial change that will let me override the content present in the notebook pane with html (right now it can only receive plain text).

**Comment by dhirschfeld** [comment]
Great! Looking forward to Jupyter4 coming out...

**Comment by dhirschfeld** [comment]
It seems this works now?
https://twitter.com/SylvainCorlay/status/926206993311961088

**Comment by SylvainCorlay** [comment]
Wow, this is an old issue! It does work indeed, since IPython 5.0.

The `sphinxify_docstrings` and `enable_html_pager` are options are opt-ins that can be set in the IPython configuration.

However, the CSS deserves some more attention to look really nice.

**Comment by dhirschfeld** [comment]
It's a great start though. I'll close this as resolved!

**Comment by ccordoba12** [comment]
> However, the CSS deserves some more attention to look really nice.

Sure, I agree completely. We'll work on it for Spyder 4 because we plan to make `docrepr` a hard dependency.
