### ISSUE TITLE
Matplotlib images not located properly

### ISSUE THREAD

**Issue by martinRenou** [spyder-ide/docrepr#31]
When using the plot_directive, the HTML file seems to look for Matplotlib screenshots under the `_images` directory, while they are at the same level as the HTML file:

![plotdirective](https://user-images.githubusercontent.com/21197331/145550318-3c0ccf8a-d2cb-4181-8ff0-ed86d6d8852d.png)

![dir](https://user-images.githubusercontent.com/21197331/145550461-a36a9297-da9d-4bf3-b9d3-73ab7c504e9b.png)

From a first small investigation, this `_images` directory suffix seems to come from Matplotlib itself, we don't set it here in docrepr.

**Comment by martinRenou** [comment]
The culprit for this seems to be sphinx itself. When adding prints to [this part of sphinx](https://github.com/sphinx-doc/sphinx/blob/8fd4373d3aec07b8d9a4fb159b6236f4dc715b21/sphinx/builders/html/__init__.py#L726-L739) into:

```python
def copy_image_files(self) -> None:
    # HERE A FIRST PRINT
    print('images ', self.images)
    if self.images:
        stringify_func = ImageAdapter(self.app.env).get_original_image_uri
        ensuredir(path.join(self.outdir, self.imagedir))
        for src in status_iterator(self.images, __('copying images... '), "brown",
                                    len(self.images), self.app.verbosity,
                                    stringify_func=stringify_func):
            dest = self.images[src]
            try:
                # HERE A SECOND PRINT
                print('copy file ', path.join(self.srcdir, src),
                            path.join(self.outdir, self.imagedir, dest))
                copyfile(path.join(self.srcdir, src),
                            path.join(self.outdir, self.imagedir, dest))
            except Exception as err:
                logger.warning(__('cannot copy image file %r: %s'),
                                path.join(self.srcdir, src), err)
```

The following gets printed:
```
images  {'docstring-1.png': 'docstring-1.png'}
copy file  /tmp/tmp3qk8fyn7/docstring-1.png /tmp/tmpjjass7c0/_images/docstring-1.png
```

So sphinx seems to put all images into an `_images` directory. ~~[This doesn't seem to be taken into account by Matplotlib's `plot_directive`](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/sphinxext/plot_directive.py#L383)~~.

---

**EDIT:** 
So I actually got confused here. Sphinx seems to be trying to copy the files under an `_images` directory, which is exactly what we want. But the resulting `tmp` folder doesn't seem impacted by this?

**Comment by martinRenou** [comment]
The key issue here is `copy file  /tmp/tmp3qk8fyn7/docstring-1.png /tmp/tmpjjass7c0/_images/docstring-1.png`. It doesn't stay in the same `tmp` folder, while moving the images...

And the HTML page that's showing up is the one from `/tmp/tmp3qk8fyn7` (initial one).

**Comment by martinRenou** [comment]
The issue is actually that a temporary destination directory is created for the output of Sphinx: https://github.com/spyder-ide/docrepr/blob/master/docrepr/sphinxify.py#L293

This destination directory is never used whatsoever. We only use the output HTML file.

**Comment by martinRenou** [comment]
I am tempted to push a fix that overwrites the source directory that we create [here](https://github.com/spyder-ide/docrepr/blob/master/docrepr/sphinxify.py#L345) by making it the destination folder for sphinx. What do you think?

It seems we cannot use the same folder for source and destination with sphinx:
```
sphinx.errors.ApplicationError: Source directory and destination directory cannot be identical
```

So we'll need to create an other temporary folder that we will use to overwrite the original `srcdir`.

If you agree with this, I can push a PR making those changes.

**Comment by CAM-Gerlach** [comment]
Thanks for the detailed investigation!

> It seems we cannot use the same folder for source and destination with sphinx:

Yep, that was added in #21 to fix #16 (as approved by your own @SylvainCorlay :) ), which is why we had to create the temporary destination directory. If you have a better solution that fixes this issue (and hopefully the one I'm experiencing as well, but I guess we'll see), feel free to go for it.

**Comment by martinRenou** [comment]
Thanks for the context :) I see @minrk is also suggesting to make a temporary folder #16 so I'll go for it.

> I suppose a separate temporary directory needs to be created.

**Comment by martinRenou** [comment]
Actually we don't need another temp directory, merging the `destdir` and `srcdir` after build should be enough: #32
