### ISSUE TITLE
Quick start example?

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/docrepr#4]
It is not clear if it is a command line tool, web server or a library that requires some IDE host

**Comment by ccordoba12** [comment]
It's a library. Take a look at `fabfile.py` to see how to use it (it works with Fabric :-)

**Comment by techtonik** [comment]
@ccordoba12 I opened it, but saw only tests there. Even as a library, it still lacks the docs. =)

Like in your talk you were describing a toolchain of transforming some docstrings and metadata into html + bootstrap. The diagram can help to understand it better.

**Comment by ccordoba12** [comment]
Fixed in our Readme now.
