### ISSUE TITLE
Release Docrepr 0.2.0

### ISSUE THREAD

**Issue by SylvainCorlay** [spyder-ide/docrepr#42]
Following the various fixes and improvements that were merged recently, would there be any objection with me tagging a release of docrepr as of the current state of the master branch?

The version available on PyPI is completely non-functional, and having the current version available is currently our main blocker to move forward with the downstream use case in Jupyter. We (@SylvainCorlay, @martinrenou, @fasiha) definitely plan on continuing improving docrepr.

cc @CAM-Gerlach

**Comment by martinRenou** [comment]
I guess we can merge https://github.com/spyder-ide/docrepr/pull/41 and tag a release?

It's probably fine to fix https://github.com/spyder-ide/docrepr/issues/38 in another patch release. Tagging a release now would already be a good improvement from the current state (docrepr not working at all with latest Sphinx).

**Comment by CAM-Gerlach** [comment]
Hey, thanks for checking in and sorry for the delay! The working plan we'd discussed up till now was to cut a release as soon as #37 , #38 , #39 and #40  were resolved; I merged #40 earlier today and #41 closing #39 just now, and I'm fine with deferring #38 if you feel that's best; I bumped it to the v0.2.1 milestone.

That just leaves #37 , which has key license, meta-file and docs updates to conform to current org policy (particularly the greatly-evolved org-standard release procedure). its 4 am (CST/UTC-6) here so I've got to get some sleep, but I'll do it first thing when I get back online and then cut the release immediately after, if that's alright with you all. Sorry again for blocking on that!

Thanks!

**Comment by martinRenou** [comment]
Thanks a lot @CAM-Gerlach!

**Comment by ccordoba12** [comment]
Thanks a lot @CAM-Gerlach, @SylvainCorlay, @martinRenou and @fasiha for your help with this new release! It's really nice to see `docrepr` alive again!

**Comment by CAM-Gerlach** [comment]
Thanks for helping support it, @ccordoba12 !
